services:
  db:
    build: ./database
    container_name: boardgames-db
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "7171:5432"
    networks:
      - boardgames-network

  app:
    build: ./backend
    container_name: choice-game-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/board_games_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FRONTEND_URL: http://localhost:7272
    depends_on:
      - db
      - front
    ports:
      - "7070:8080"
    networks:
      - boardgames-network
      
  front:
    build: ./frontend
    container_name: choice-game-frontend
    environment:
      BACKEND_URL: http://localhost:7070
    depends_on:
      - app
    ports:
      - "7272:8080"
    networks:
      - boardgames-network

networks:
  boardgames-network:
    driver: bridge
